/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAgendaRouteImport } from './routes/_authenticated/agenda'
import { Route as AuthenticatedBenefitsRouteImport } from './routes/_authenticated/benefits'
import { Route as AuthenticatedChatRouteImport } from './routes/_authenticated/chat'
import { Route as AuthenticatedDecideRouteImport } from './routes/_authenticated/decide'
import { Route as AuthenticatedDocsRouteImport } from './routes/_authenticated/docs'
import { Route as AuthenticatedFamilyRouteImport } from './routes/_authenticated/family'
import { Route as AuthenticatedHelperDashboardRouteImport } from './routes/_authenticated/helper-dashboard'
import { Route as AuthenticatedHelpmeRouteImport } from './routes/_authenticated/helpme'
import { Route as AuthenticatedInboxRouteImport } from './routes/_authenticated/inbox'
import { Route as AuthenticatedLegacyRouteImport } from './routes/_authenticated/legacy'
import { Route as AuthenticatedLocalRouteImport } from './routes/_authenticated/local'
import { Route as AuthenticatedMoneyRouteImport } from './routes/_authenticated/money'
import { Route as AuthenticatedSearchRouteImport } from './routes/_authenticated/search'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedSupportRouteImport } from './routes/_authenticated/support'
import { Route as AuthenticatedTasksRouteImport } from './routes/_authenticated/tasks'
import { Route as AuthenticatedTodayRouteImport } from './routes/_authenticated/today'
import { Route as BenefitsShareTokenRouteImport } from './routes/benefits-share.$token'
import { Route as LineCallbackRouteImport } from './routes/line/callback'
import { Route as MemorialTokenRouteImport } from './routes/memorial.$token'
import { Route as SsoCallbackRouteImport } from './routes/sso/callback'
import { Route as AuthenticatedAdminFuneralRouteImport } from './routes/_authenticated/admin_.funeral'
import { Route as AuthenticatedAdminMarketplaceRouteImport } from './routes/_authenticated/admin_.marketplace'
import { Route as AuthenticatedAdminPaymentsRouteImport } from './routes/_authenticated/admin_.payments'
import { Route as AuthenticatedAdminPremiumRouteImport } from './routes/_authenticated/admin_.premium'
import { Route as AuthenticatedAdminRulesRouteImport } from './routes/_authenticated/admin_.rules'
import { Route as AuthenticatedAdminSafetyRouteImport } from './routes/_authenticated/admin_.safety'
import { Route as AuthenticatedAdminSupportRouteImport } from './routes/_authenticated/admin_.support'
import { Route as AuthenticatedAdminUsageRouteImport } from './routes/_authenticated/admin_.usage'
import { Route as AuthenticatedFamilyTimelineRouteImport } from './routes/_authenticated/family_.timeline'
import { Route as AuthenticatedLegacyAfterRouteImport } from './routes/_authenticated/legacy_.after'
import { Route as AuthenticatedLocalMerchantRouteImport } from './routes/_authenticated/local_.merchant'
import { Route as AuthenticatedLegacyInviteTokenRouteImport } from './routes/_authenticated/legacy_.invite.$token'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAgendaRoute = AuthenticatedAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBenefitsRoute = AuthenticatedBenefitsRouteImport.update({
  id: '/benefits',
  path: '/benefits',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChatRoute = AuthenticatedChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDecideRoute = AuthenticatedDecideRouteImport.update({
  id: '/decide',
  path: '/decide',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDocsRoute = AuthenticatedDocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFamilyRoute = AuthenticatedFamilyRouteImport.update({
  id: '/family',
  path: '/family',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHelperDashboardRoute =
  AuthenticatedHelperDashboardRouteImport.update({
    id: '/helper-dashboard',
    path: '/helper-dashboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHelpmeRoute = AuthenticatedHelpmeRouteImport.update({
  id: '/helpme',
  path: '/helpme',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInboxRoute = AuthenticatedInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLegacyRoute = AuthenticatedLegacyRouteImport.update({
  id: '/legacy',
  path: '/legacy',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLocalRoute = AuthenticatedLocalRouteImport.update({
  id: '/local',
  path: '/local',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMoneyRoute = AuthenticatedMoneyRouteImport.update({
  id: '/money',
  path: '/money',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSearchRoute = AuthenticatedSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSupportRoute = AuthenticatedSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTasksRoute = AuthenticatedTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTodayRoute = AuthenticatedTodayRouteImport.update({
  id: '/today',
  path: '/today',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const BenefitsShareTokenRoute = BenefitsShareTokenRouteImport.update({
  id: '/benefits-share/$token',
  path: '/benefits-share/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const LineCallbackRoute = LineCallbackRouteImport.update({
  id: '/line/callback',
  path: '/line/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const MemorialTokenRoute = MemorialTokenRouteImport.update({
  id: '/memorial/$token',
  path: '/memorial/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const SsoCallbackRoute = SsoCallbackRouteImport.update({
  id: '/sso/callback',
  path: '/sso/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminFuneralRoute =
  AuthenticatedAdminFuneralRouteImport.update({
    id: '/admin_/funeral',
    path: '/admin/funeral',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminMarketplaceRoute =
  AuthenticatedAdminMarketplaceRouteImport.update({
    id: '/admin_/marketplace',
    path: '/admin/marketplace',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminPaymentsRoute =
  AuthenticatedAdminPaymentsRouteImport.update({
    id: '/admin_/payments',
    path: '/admin/payments',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminPremiumRoute =
  AuthenticatedAdminPremiumRouteImport.update({
    id: '/admin_/premium',
    path: '/admin/premium',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminRulesRoute = AuthenticatedAdminRulesRouteImport.update({
  id: '/admin_/rules',
  path: '/admin/rules',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminSafetyRoute =
  AuthenticatedAdminSafetyRouteImport.update({
    id: '/admin_/safety',
    path: '/admin/safety',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminSupportRoute =
  AuthenticatedAdminSupportRouteImport.update({
    id: '/admin_/support',
    path: '/admin/support',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminUsageRoute = AuthenticatedAdminUsageRouteImport.update({
  id: '/admin_/usage',
  path: '/admin/usage',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFamilyTimelineRoute =
  AuthenticatedFamilyTimelineRouteImport.update({
    id: '/family_/timeline',
    path: '/family/timeline',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLegacyAfterRoute =
  AuthenticatedLegacyAfterRouteImport.update({
    id: '/legacy_/after',
    path: '/legacy/after',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLocalMerchantRoute =
  AuthenticatedLocalMerchantRouteImport.update({
    id: '/local_/merchant',
    path: '/local/merchant',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLegacyInviteTokenRoute =
  AuthenticatedLegacyInviteTokenRouteImport.update({
    id: '/legacy_/invite/$token',
    path: '/legacy/invite/$token',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/agenda': typeof AuthenticatedAgendaRoute
  '/benefits': typeof AuthenticatedBenefitsRoute
  '/chat': typeof AuthenticatedChatRoute
  '/decide': typeof AuthenticatedDecideRoute
  '/docs': typeof AuthenticatedDocsRoute
  '/family': typeof AuthenticatedFamilyRoute
  '/helper-dashboard': typeof AuthenticatedHelperDashboardRoute
  '/helpme': typeof AuthenticatedHelpmeRoute
  '/inbox': typeof AuthenticatedInboxRoute
  '/legacy': typeof AuthenticatedLegacyRoute
  '/local': typeof AuthenticatedLocalRoute
  '/money': typeof AuthenticatedMoneyRoute
  '/search': typeof AuthenticatedSearchRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/support': typeof AuthenticatedSupportRoute
  '/tasks': typeof AuthenticatedTasksRoute
  '/today': typeof AuthenticatedTodayRoute
  '/benefits-share/$token': typeof BenefitsShareTokenRoute
  '/line/callback': typeof LineCallbackRoute
  '/memorial/$token': typeof MemorialTokenRoute
  '/sso/callback': typeof SsoCallbackRoute
  '/admin/funeral': typeof AuthenticatedAdminFuneralRoute
  '/admin/marketplace': typeof AuthenticatedAdminMarketplaceRoute
  '/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/admin/premium': typeof AuthenticatedAdminPremiumRoute
  '/admin/rules': typeof AuthenticatedAdminRulesRoute
  '/admin/safety': typeof AuthenticatedAdminSafetyRoute
  '/admin/support': typeof AuthenticatedAdminSupportRoute
  '/admin/usage': typeof AuthenticatedAdminUsageRoute
  '/family/timeline': typeof AuthenticatedFamilyTimelineRoute
  '/legacy/after': typeof AuthenticatedLegacyAfterRoute
  '/local/merchant': typeof AuthenticatedLocalMerchantRoute
  '/legacy/invite/$token': typeof AuthenticatedLegacyInviteTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/agenda': typeof AuthenticatedAgendaRoute
  '/benefits': typeof AuthenticatedBenefitsRoute
  '/chat': typeof AuthenticatedChatRoute
  '/decide': typeof AuthenticatedDecideRoute
  '/docs': typeof AuthenticatedDocsRoute
  '/family': typeof AuthenticatedFamilyRoute
  '/helper-dashboard': typeof AuthenticatedHelperDashboardRoute
  '/helpme': typeof AuthenticatedHelpmeRoute
  '/inbox': typeof AuthenticatedInboxRoute
  '/legacy': typeof AuthenticatedLegacyRoute
  '/local': typeof AuthenticatedLocalRoute
  '/money': typeof AuthenticatedMoneyRoute
  '/search': typeof AuthenticatedSearchRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/support': typeof AuthenticatedSupportRoute
  '/tasks': typeof AuthenticatedTasksRoute
  '/today': typeof AuthenticatedTodayRoute
  '/benefits-share/$token': typeof BenefitsShareTokenRoute
  '/line/callback': typeof LineCallbackRoute
  '/memorial/$token': typeof MemorialTokenRoute
  '/sso/callback': typeof SsoCallbackRoute
  '/admin/funeral': typeof AuthenticatedAdminFuneralRoute
  '/admin/marketplace': typeof AuthenticatedAdminMarketplaceRoute
  '/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/admin/premium': typeof AuthenticatedAdminPremiumRoute
  '/admin/rules': typeof AuthenticatedAdminRulesRoute
  '/admin/safety': typeof AuthenticatedAdminSafetyRoute
  '/admin/support': typeof AuthenticatedAdminSupportRoute
  '/admin/usage': typeof AuthenticatedAdminUsageRoute
  '/family/timeline': typeof AuthenticatedFamilyTimelineRoute
  '/legacy/after': typeof AuthenticatedLegacyAfterRoute
  '/local/merchant': typeof AuthenticatedLocalMerchantRoute
  '/legacy/invite/$token': typeof AuthenticatedLegacyInviteTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/agenda': typeof AuthenticatedAgendaRoute
  '/_authenticated/benefits': typeof AuthenticatedBenefitsRoute
  '/_authenticated/chat': typeof AuthenticatedChatRoute
  '/_authenticated/decide': typeof AuthenticatedDecideRoute
  '/_authenticated/docs': typeof AuthenticatedDocsRoute
  '/_authenticated/family': typeof AuthenticatedFamilyRoute
  '/_authenticated/helper-dashboard': typeof AuthenticatedHelperDashboardRoute
  '/_authenticated/helpme': typeof AuthenticatedHelpmeRoute
  '/_authenticated/inbox': typeof AuthenticatedInboxRoute
  '/_authenticated/legacy': typeof AuthenticatedLegacyRoute
  '/_authenticated/local': typeof AuthenticatedLocalRoute
  '/_authenticated/money': typeof AuthenticatedMoneyRoute
  '/_authenticated/search': typeof AuthenticatedSearchRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/support': typeof AuthenticatedSupportRoute
  '/_authenticated/tasks': typeof AuthenticatedTasksRoute
  '/_authenticated/today': typeof AuthenticatedTodayRoute
  '/benefits-share/$token': typeof BenefitsShareTokenRoute
  '/line/callback': typeof LineCallbackRoute
  '/memorial/$token': typeof MemorialTokenRoute
  '/sso/callback': typeof SsoCallbackRoute
  '/_authenticated/admin_/funeral': typeof AuthenticatedAdminFuneralRoute
  '/_authenticated/admin_/marketplace': typeof AuthenticatedAdminMarketplaceRoute
  '/_authenticated/admin_/payments': typeof AuthenticatedAdminPaymentsRoute
  '/_authenticated/admin_/premium': typeof AuthenticatedAdminPremiumRoute
  '/_authenticated/admin_/rules': typeof AuthenticatedAdminRulesRoute
  '/_authenticated/admin_/safety': typeof AuthenticatedAdminSafetyRoute
  '/_authenticated/admin_/support': typeof AuthenticatedAdminSupportRoute
  '/_authenticated/admin_/usage': typeof AuthenticatedAdminUsageRoute
  '/_authenticated/family_/timeline': typeof AuthenticatedFamilyTimelineRoute
  '/_authenticated/legacy_/after': typeof AuthenticatedLegacyAfterRoute
  '/_authenticated/local_/merchant': typeof AuthenticatedLocalMerchantRoute
  '/_authenticated/legacy_/invite/$token': typeof AuthenticatedLegacyInviteTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/agenda'
    | '/benefits'
    | '/chat'
    | '/decide'
    | '/docs'
    | '/family'
    | '/helper-dashboard'
    | '/helpme'
    | '/inbox'
    | '/legacy'
    | '/local'
    | '/money'
    | '/search'
    | '/settings'
    | '/support'
    | '/tasks'
    | '/today'
    | '/benefits-share/$token'
    | '/line/callback'
    | '/memorial/$token'
    | '/sso/callback'
    | '/admin/funeral'
    | '/admin/marketplace'
    | '/admin/payments'
    | '/admin/premium'
    | '/admin/rules'
    | '/admin/safety'
    | '/admin/support'
    | '/admin/usage'
    | '/family/timeline'
    | '/legacy/after'
    | '/local/merchant'
    | '/legacy/invite/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin'
    | '/agenda'
    | '/benefits'
    | '/chat'
    | '/decide'
    | '/docs'
    | '/family'
    | '/helper-dashboard'
    | '/helpme'
    | '/inbox'
    | '/legacy'
    | '/local'
    | '/money'
    | '/search'
    | '/settings'
    | '/support'
    | '/tasks'
    | '/today'
    | '/benefits-share/$token'
    | '/line/callback'
    | '/memorial/$token'
    | '/sso/callback'
    | '/admin/funeral'
    | '/admin/marketplace'
    | '/admin/payments'
    | '/admin/premium'
    | '/admin/rules'
    | '/admin/safety'
    | '/admin/support'
    | '/admin/usage'
    | '/family/timeline'
    | '/legacy/after'
    | '/local/merchant'
    | '/legacy/invite/$token'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin'
    | '/_authenticated/agenda'
    | '/_authenticated/benefits'
    | '/_authenticated/chat'
    | '/_authenticated/decide'
    | '/_authenticated/docs'
    | '/_authenticated/family'
    | '/_authenticated/helper-dashboard'
    | '/_authenticated/helpme'
    | '/_authenticated/inbox'
    | '/_authenticated/legacy'
    | '/_authenticated/local'
    | '/_authenticated/money'
    | '/_authenticated/search'
    | '/_authenticated/settings'
    | '/_authenticated/support'
    | '/_authenticated/tasks'
    | '/_authenticated/today'
    | '/benefits-share/$token'
    | '/line/callback'
    | '/memorial/$token'
    | '/sso/callback'
    | '/_authenticated/admin_/funeral'
    | '/_authenticated/admin_/marketplace'
    | '/_authenticated/admin_/payments'
    | '/_authenticated/admin_/premium'
    | '/_authenticated/admin_/rules'
    | '/_authenticated/admin_/safety'
    | '/_authenticated/admin_/support'
    | '/_authenticated/admin_/usage'
    | '/_authenticated/family_/timeline'
    | '/_authenticated/legacy_/after'
    | '/_authenticated/local_/merchant'
    | '/_authenticated/legacy_/invite/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  BenefitsShareTokenRoute: typeof BenefitsShareTokenRoute
  LineCallbackRoute: typeof LineCallbackRoute
  MemorialTokenRoute: typeof MemorialTokenRoute
  SsoCallbackRoute: typeof SsoCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/agenda': {
      id: '/_authenticated/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AuthenticatedAgendaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/benefits': {
      id: '/_authenticated/benefits'
      path: '/benefits'
      fullPath: '/benefits'
      preLoaderRoute: typeof AuthenticatedBenefitsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chat': {
      id: '/_authenticated/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AuthenticatedChatRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/decide': {
      id: '/_authenticated/decide'
      path: '/decide'
      fullPath: '/decide'
      preLoaderRoute: typeof AuthenticatedDecideRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/docs': {
      id: '/_authenticated/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof AuthenticatedDocsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/family': {
      id: '/_authenticated/family'
      path: '/family'
      fullPath: '/family'
      preLoaderRoute: typeof AuthenticatedFamilyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/helper-dashboard': {
      id: '/_authenticated/helper-dashboard'
      path: '/helper-dashboard'
      fullPath: '/helper-dashboard'
      preLoaderRoute: typeof AuthenticatedHelperDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/helpme': {
      id: '/_authenticated/helpme'
      path: '/helpme'
      fullPath: '/helpme'
      preLoaderRoute: typeof AuthenticatedHelpmeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inbox': {
      id: '/_authenticated/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof AuthenticatedInboxRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/legacy': {
      id: '/_authenticated/legacy'
      path: '/legacy'
      fullPath: '/legacy'
      preLoaderRoute: typeof AuthenticatedLegacyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/local': {
      id: '/_authenticated/local'
      path: '/local'
      fullPath: '/local'
      preLoaderRoute: typeof AuthenticatedLocalRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/money': {
      id: '/_authenticated/money'
      path: '/money'
      fullPath: '/money'
      preLoaderRoute: typeof AuthenticatedMoneyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/search': {
      id: '/_authenticated/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AuthenticatedSearchRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/support': {
      id: '/_authenticated/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof AuthenticatedSupportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tasks': {
      id: '/_authenticated/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AuthenticatedTasksRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/today': {
      id: '/_authenticated/today'
      path: '/today'
      fullPath: '/today'
      preLoaderRoute: typeof AuthenticatedTodayRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/benefits-share/$token': {
      id: '/benefits-share/$token'
      path: '/benefits-share/$token'
      fullPath: '/benefits-share/$token'
      preLoaderRoute: typeof BenefitsShareTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/line/callback': {
      id: '/line/callback'
      path: '/line/callback'
      fullPath: '/line/callback'
      preLoaderRoute: typeof LineCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memorial/$token': {
      id: '/memorial/$token'
      path: '/memorial/$token'
      fullPath: '/memorial/$token'
      preLoaderRoute: typeof MemorialTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sso/callback': {
      id: '/sso/callback'
      path: '/sso/callback'
      fullPath: '/sso/callback'
      preLoaderRoute: typeof SsoCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin_/funeral': {
      id: '/_authenticated/admin_/funeral'
      path: '/admin/funeral'
      fullPath: '/admin/funeral'
      preLoaderRoute: typeof AuthenticatedAdminFuneralRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin_/marketplace': {
      id: '/_authenticated/admin_/marketplace'
      path: '/admin/marketplace'
      fullPath: '/admin/marketplace'
      preLoaderRoute: typeof AuthenticatedAdminMarketplaceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin_/payments': {
      id: '/_authenticated/admin_/payments'
      path: '/admin/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AuthenticatedAdminPaymentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin_/premium': {
      id: '/_authenticated/admin_/premium'
      path: '/admin/premium'
      fullPath: '/admin/premium'
      preLoaderRoute: typeof AuthenticatedAdminPremiumRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin_/rules': {
      id: '/_authenticated/admin_/rules'
      path: '/admin/rules'
      fullPath: '/admin/rules'
      preLoaderRoute: typeof AuthenticatedAdminRulesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin_/safety': {
      id: '/_authenticated/admin_/safety'
      path: '/admin/safety'
      fullPath: '/admin/safety'
      preLoaderRoute: typeof AuthenticatedAdminSafetyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin_/support': {
      id: '/_authenticated/admin_/support'
      path: '/admin/support'
      fullPath: '/admin/support'
      preLoaderRoute: typeof AuthenticatedAdminSupportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin_/usage': {
      id: '/_authenticated/admin_/usage'
      path: '/admin/usage'
      fullPath: '/admin/usage'
      preLoaderRoute: typeof AuthenticatedAdminUsageRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/family_/timeline': {
      id: '/_authenticated/family_/timeline'
      path: '/family/timeline'
      fullPath: '/family/timeline'
      preLoaderRoute: typeof AuthenticatedFamilyTimelineRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/legacy_/after': {
      id: '/_authenticated/legacy_/after'
      path: '/legacy/after'
      fullPath: '/legacy/after'
      preLoaderRoute: typeof AuthenticatedLegacyAfterRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/local_/merchant': {
      id: '/_authenticated/local_/merchant'
      path: '/local/merchant'
      fullPath: '/local/merchant'
      preLoaderRoute: typeof AuthenticatedLocalMerchantRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/legacy_/invite/$token': {
      id: '/_authenticated/legacy_/invite/$token'
      path: '/legacy/invite/$token'
      fullPath: '/legacy/invite/$token'
      preLoaderRoute: typeof AuthenticatedLegacyInviteTokenRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedAgendaRoute: typeof AuthenticatedAgendaRoute
  AuthenticatedBenefitsRoute: typeof AuthenticatedBenefitsRoute
  AuthenticatedChatRoute: typeof AuthenticatedChatRoute
  AuthenticatedDecideRoute: typeof AuthenticatedDecideRoute
  AuthenticatedDocsRoute: typeof AuthenticatedDocsRoute
  AuthenticatedFamilyRoute: typeof AuthenticatedFamilyRoute
  AuthenticatedHelperDashboardRoute: typeof AuthenticatedHelperDashboardRoute
  AuthenticatedHelpmeRoute: typeof AuthenticatedHelpmeRoute
  AuthenticatedInboxRoute: typeof AuthenticatedInboxRoute
  AuthenticatedLegacyRoute: typeof AuthenticatedLegacyRoute
  AuthenticatedLocalRoute: typeof AuthenticatedLocalRoute
  AuthenticatedMoneyRoute: typeof AuthenticatedMoneyRoute
  AuthenticatedSearchRoute: typeof AuthenticatedSearchRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedSupportRoute: typeof AuthenticatedSupportRoute
  AuthenticatedTasksRoute: typeof AuthenticatedTasksRoute
  AuthenticatedTodayRoute: typeof AuthenticatedTodayRoute
  AuthenticatedAdminFuneralRoute: typeof AuthenticatedAdminFuneralRoute
  AuthenticatedAdminMarketplaceRoute: typeof AuthenticatedAdminMarketplaceRoute
  AuthenticatedAdminPaymentsRoute: typeof AuthenticatedAdminPaymentsRoute
  AuthenticatedAdminPremiumRoute: typeof AuthenticatedAdminPremiumRoute
  AuthenticatedAdminRulesRoute: typeof AuthenticatedAdminRulesRoute
  AuthenticatedAdminSafetyRoute: typeof AuthenticatedAdminSafetyRoute
  AuthenticatedAdminSupportRoute: typeof AuthenticatedAdminSupportRoute
  AuthenticatedAdminUsageRoute: typeof AuthenticatedAdminUsageRoute
  AuthenticatedFamilyTimelineRoute: typeof AuthenticatedFamilyTimelineRoute
  AuthenticatedLegacyAfterRoute: typeof AuthenticatedLegacyAfterRoute
  AuthenticatedLocalMerchantRoute: typeof AuthenticatedLocalMerchantRoute
  AuthenticatedLegacyInviteTokenRoute: typeof AuthenticatedLegacyInviteTokenRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedAgendaRoute: AuthenticatedAgendaRoute,
  AuthenticatedBenefitsRoute: AuthenticatedBenefitsRoute,
  AuthenticatedChatRoute: AuthenticatedChatRoute,
  AuthenticatedDecideRoute: AuthenticatedDecideRoute,
  AuthenticatedDocsRoute: AuthenticatedDocsRoute,
  AuthenticatedFamilyRoute: AuthenticatedFamilyRoute,
  AuthenticatedHelperDashboardRoute: AuthenticatedHelperDashboardRoute,
  AuthenticatedHelpmeRoute: AuthenticatedHelpmeRoute,
  AuthenticatedInboxRoute: AuthenticatedInboxRoute,
  AuthenticatedLegacyRoute: AuthenticatedLegacyRoute,
  AuthenticatedLocalRoute: AuthenticatedLocalRoute,
  AuthenticatedMoneyRoute: AuthenticatedMoneyRoute,
  AuthenticatedSearchRoute: AuthenticatedSearchRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedSupportRoute: AuthenticatedSupportRoute,
  AuthenticatedTasksRoute: AuthenticatedTasksRoute,
  AuthenticatedTodayRoute: AuthenticatedTodayRoute,
  AuthenticatedAdminFuneralRoute: AuthenticatedAdminFuneralRoute,
  AuthenticatedAdminMarketplaceRoute: AuthenticatedAdminMarketplaceRoute,
  AuthenticatedAdminPaymentsRoute: AuthenticatedAdminPaymentsRoute,
  AuthenticatedAdminPremiumRoute: AuthenticatedAdminPremiumRoute,
  AuthenticatedAdminRulesRoute: AuthenticatedAdminRulesRoute,
  AuthenticatedAdminSafetyRoute: AuthenticatedAdminSafetyRoute,
  AuthenticatedAdminSupportRoute: AuthenticatedAdminSupportRoute,
  AuthenticatedAdminUsageRoute: AuthenticatedAdminUsageRoute,
  AuthenticatedFamilyTimelineRoute: AuthenticatedFamilyTimelineRoute,
  AuthenticatedLegacyAfterRoute: AuthenticatedLegacyAfterRoute,
  AuthenticatedLocalMerchantRoute: AuthenticatedLocalMerchantRoute,
  AuthenticatedLegacyInviteTokenRoute: AuthenticatedLegacyInviteTokenRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  BenefitsShareTokenRoute: BenefitsShareTokenRoute,
  LineCallbackRoute: LineCallbackRoute,
  MemorialTokenRoute: MemorialTokenRoute,
  SsoCallbackRoute: SsoCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
