/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as MicTestRouteImport } from './routes/mic-test'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedBenefitsRouteImport } from './routes/_authenticated/benefits'
import { Route as AuthenticatedDecideRouteImport } from './routes/_authenticated/decide'
import { Route as AuthenticatedHelperDashboardRouteImport } from './routes/_authenticated/helper-dashboard'
import { Route as AuthenticatedAdminMarketplaceRouteImport } from './routes/_authenticated/admin_.marketplace'
import { Route as AuthenticatedAdminSafetyRouteImport } from './routes/_authenticated/admin_.safety'
import { Route as AuthenticatedLocalRouteImport } from './routes/_authenticated/local'
import { Route as AuthenticatedLocalMerchantRouteImport } from './routes/_authenticated/local_.merchant'
import { Route as AuthenticatedChatRouteImport } from './routes/_authenticated/chat'
import { Route as AuthenticatedDocsRouteImport } from './routes/_authenticated/docs'
import { Route as AuthenticatedFamilyRouteImport } from './routes/_authenticated/family'
import { Route as AuthenticatedHelpmeRouteImport } from './routes/_authenticated/helpme'
import { Route as AuthenticatedMoneyRouteImport } from './routes/_authenticated/money'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedSupportRouteImport } from './routes/_authenticated/support'
import { Route as AuthenticatedTasksRouteImport } from './routes/_authenticated/tasks'
import { Route as AuthenticatedTodayRouteImport } from './routes/_authenticated/today'
import { Route as LineCallbackRouteImport } from './routes/line/callback'
import { Route as SsoCallbackRouteImport } from './routes/sso/callback'
import { Route as AuthenticatedAdminSupportRouteImport } from './routes/_authenticated/admin_.support'
import { Route as AuthenticatedAdminPaymentsRouteImport } from './routes/_authenticated/admin_.payments'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const MicTestRoute = MicTestRouteImport.update({
  id: '/mic-test',
  path: '/mic-test',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBenefitsRoute = AuthenticatedBenefitsRouteImport.update({
  id: '/benefits',
  path: '/benefits',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLocalRoute = AuthenticatedLocalRouteImport.update({
  id: '/local',
  path: '/local',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLocalMerchantRoute = AuthenticatedLocalMerchantRouteImport.update({
  id: '/local_/merchant',
  path: '/local/merchant',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

const AuthenticatedDecideRoute = AuthenticatedDecideRouteImport.update({
  id: '/decide',
  path: '/decide',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHelperDashboardRoute = AuthenticatedHelperDashboardRouteImport.update({
  id: '/helper-dashboard',
  path: '/helper-dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminMarketplaceRoute = AuthenticatedAdminMarketplaceRouteImport.update({
  id: '/admin_/marketplace',
  path: '/admin/marketplace',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminSafetyRoute = AuthenticatedAdminSafetyRouteImport.update({
  id: '/admin_/safety',
  path: '/admin/safety',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChatRoute = AuthenticatedChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDocsRoute = AuthenticatedDocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFamilyRoute = AuthenticatedFamilyRouteImport.update({
  id: '/family',
  path: '/family',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHelpmeRoute = AuthenticatedHelpmeRouteImport.update({
  id: '/helpme',
  path: '/helpme',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMoneyRoute = AuthenticatedMoneyRouteImport.update({
  id: '/money',
  path: '/money',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSupportRoute = AuthenticatedSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTasksRoute = AuthenticatedTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTodayRoute = AuthenticatedTodayRouteImport.update({
  id: '/today',
  path: '/today',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const LineCallbackRoute = LineCallbackRouteImport.update({
  id: '/line/callback',
  path: '/line/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const SsoCallbackRoute = SsoCallbackRouteImport.update({
  id: '/sso/callback',
  path: '/sso/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminSupportRoute =
  AuthenticatedAdminSupportRouteImport.update({
    id: '/admin_/support',
    path: '/admin/support',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminPaymentsRoute =
  AuthenticatedAdminPaymentsRouteImport.update({
    id: '/admin_/payments',
    path: '/admin/payments',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/mic-test': typeof MicTestRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/benefits': typeof AuthenticatedBenefitsRoute
  '/local': typeof AuthenticatedLocalRoute
  '/local/merchant': typeof AuthenticatedLocalMerchantRoute
  '/decide': typeof AuthenticatedDecideRoute
  '/helper-dashboard': typeof AuthenticatedHelperDashboardRoute
  '/admin/marketplace': typeof AuthenticatedAdminMarketplaceRoute
  '/admin/safety': typeof AuthenticatedAdminSafetyRoute
  '/chat': typeof AuthenticatedChatRoute
  '/docs': typeof AuthenticatedDocsRoute
  '/family': typeof AuthenticatedFamilyRoute
  '/helpme': typeof AuthenticatedHelpmeRoute
  '/money': typeof AuthenticatedMoneyRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/support': typeof AuthenticatedSupportRoute
  '/tasks': typeof AuthenticatedTasksRoute
  '/today': typeof AuthenticatedTodayRoute
  '/line/callback': typeof LineCallbackRoute
  '/sso/callback': typeof SsoCallbackRoute
  '/admin/support': typeof AuthenticatedAdminSupportRoute
  '/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/admin/payments': typeof AuthenticatedAdminPaymentsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/mic-test': typeof MicTestRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/benefits': typeof AuthenticatedBenefitsRoute
  '/local': typeof AuthenticatedLocalRoute
  '/local/merchant': typeof AuthenticatedLocalMerchantRoute
  '/decide': typeof AuthenticatedDecideRoute
  '/helper-dashboard': typeof AuthenticatedHelperDashboardRoute
  '/admin/marketplace': typeof AuthenticatedAdminMarketplaceRoute
  '/admin/safety': typeof AuthenticatedAdminSafetyRoute
  '/chat': typeof AuthenticatedChatRoute
  '/docs': typeof AuthenticatedDocsRoute
  '/family': typeof AuthenticatedFamilyRoute
  '/helpme': typeof AuthenticatedHelpmeRoute
  '/money': typeof AuthenticatedMoneyRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/support': typeof AuthenticatedSupportRoute
  '/tasks': typeof AuthenticatedTasksRoute
  '/today': typeof AuthenticatedTodayRoute
  '/line/callback': typeof LineCallbackRoute
  '/sso/callback': typeof SsoCallbackRoute
  '/admin/support': typeof AuthenticatedAdminSupportRoute
  '/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/admin/payments': typeof AuthenticatedAdminPaymentsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/mic-test': typeof MicTestRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/benefits': typeof AuthenticatedBenefitsRoute
  '/_authenticated/local': typeof AuthenticatedLocalRoute
  '/_authenticated/local_/merchant': typeof AuthenticatedLocalMerchantRoute
  '/_authenticated/decide': typeof AuthenticatedDecideRoute
  '/_authenticated/helper-dashboard': typeof AuthenticatedHelperDashboardRoute
  '/_authenticated/admin_/marketplace': typeof AuthenticatedAdminMarketplaceRoute
  '/_authenticated/admin_/safety': typeof AuthenticatedAdminSafetyRoute
  '/_authenticated/chat': typeof AuthenticatedChatRoute
  '/_authenticated/docs': typeof AuthenticatedDocsRoute
  '/_authenticated/family': typeof AuthenticatedFamilyRoute
  '/_authenticated/helpme': typeof AuthenticatedHelpmeRoute
  '/_authenticated/money': typeof AuthenticatedMoneyRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/support': typeof AuthenticatedSupportRoute
  '/_authenticated/tasks': typeof AuthenticatedTasksRoute
  '/_authenticated/today': typeof AuthenticatedTodayRoute
  '/line/callback': typeof LineCallbackRoute
  '/sso/callback': typeof SsoCallbackRoute
  '/_authenticated/admin_/support': typeof AuthenticatedAdminSupportRoute
  '/_authenticated/admin_/payments': typeof AuthenticatedAdminPaymentsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/mic-test'
    | '/admin'
    | '/benefits'
    | '/local'
    | '/local/merchant'
    | '/decide'
    | '/helper-dashboard'
    | '/admin/marketplace'
    | '/admin/safety'
    | '/chat'
    | '/docs'
    | '/family'
    | '/helpme'
    | '/money'
    | '/settings'
    | '/support'
    | '/tasks'
    | '/today'
    | '/line/callback'
    | '/sso/callback'
    | '/admin/support'
    | '/admin/payments'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/mic-test'
    | '/admin'
    | '/benefits'
    | '/local'
    | '/local/merchant'
    | '/decide'
    | '/helper-dashboard'
    | '/admin/marketplace'
    | '/admin/safety'
    | '/chat'
    | '/docs'
    | '/family'
    | '/helpme'
    | '/money'
    | '/settings'
    | '/support'
    | '/tasks'
    | '/today'
    | '/line/callback'
    | '/sso/callback'
    | '/admin/support'
    | '/admin/payments'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/mic-test'
    | '/_authenticated/admin'
    | '/_authenticated/benefits'
    | '/_authenticated/local'
    | '/_authenticated/local_/merchant'
    | '/_authenticated/chat'
    | '/_authenticated/docs'
    | '/_authenticated/family'
    | '/_authenticated/helpme'
    | '/_authenticated/money'
    | '/_authenticated/settings'
    | '/_authenticated/support'
    | '/_authenticated/tasks'
    | '/_authenticated/today'
    | '/line/callback'
    | '/sso/callback'
    | '/_authenticated/admin_/support'
    | '/_authenticated/admin_/payments'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  MicTestRoute: typeof MicTestRoute
  LineCallbackRoute: typeof LineCallbackRoute
  SsoCallbackRoute: typeof SsoCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mic-test': {
      id: '/mic-test'
      path: '/mic-test'
      fullPath: '/mic-test'
      preLoaderRoute: typeof MicTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/benefits': {
      id: '/_authenticated/benefits'
      path: '/benefits'
      fullPath: '/benefits'
      preLoaderRoute: typeof AuthenticatedBenefitsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chat': {
      id: '/_authenticated/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AuthenticatedChatRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/docs': {
      id: '/_authenticated/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof AuthenticatedDocsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/family': {
      id: '/_authenticated/family'
      path: '/family'
      fullPath: '/family'
      preLoaderRoute: typeof AuthenticatedFamilyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/helpme': {
      id: '/_authenticated/helpme'
      path: '/helpme'
      fullPath: '/helpme'
      preLoaderRoute: typeof AuthenticatedHelpmeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/money': {
      id: '/_authenticated/money'
      path: '/money'
      fullPath: '/money'
      preLoaderRoute: typeof AuthenticatedMoneyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/support': {
      id: '/_authenticated/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof AuthenticatedSupportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tasks': {
      id: '/_authenticated/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AuthenticatedTasksRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/today': {
      id: '/_authenticated/today'
      path: '/today'
      fullPath: '/today'
      preLoaderRoute: typeof AuthenticatedTodayRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/line/callback': {
      id: '/line/callback'
      path: '/line/callback'
      fullPath: '/line/callback'
      preLoaderRoute: typeof LineCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sso/callback': {
      id: '/sso/callback'
      path: '/sso/callback'
      fullPath: '/sso/callback'
      preLoaderRoute: typeof SsoCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin_/support': {
      id: '/_authenticated/admin_/support'
      path: '/admin/support'
      fullPath: '/admin/support'
      preLoaderRoute: typeof AuthenticatedAdminSupportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin_/payments': {
      id: '/_authenticated/admin_/payments'
      path: '/admin/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AuthenticatedAdminPaymentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedBenefitsRoute: typeof AuthenticatedBenefitsRoute
  AuthenticatedLocalRoute: typeof AuthenticatedLocalRoute
  AuthenticatedLocalMerchantRoute: typeof AuthenticatedLocalMerchantRoute
  AuthenticatedDecideRoute: typeof AuthenticatedDecideRoute
  AuthenticatedHelperDashboardRoute: typeof AuthenticatedHelperDashboardRoute
  AuthenticatedAdminMarketplaceRoute: typeof AuthenticatedAdminMarketplaceRoute
  AuthenticatedAdminSafetyRoute: typeof AuthenticatedAdminSafetyRoute
  AuthenticatedChatRoute: typeof AuthenticatedChatRoute
  AuthenticatedDocsRoute: typeof AuthenticatedDocsRoute
  AuthenticatedFamilyRoute: typeof AuthenticatedFamilyRoute
  AuthenticatedHelpmeRoute: typeof AuthenticatedHelpmeRoute
  AuthenticatedMoneyRoute: typeof AuthenticatedMoneyRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedSupportRoute: typeof AuthenticatedSupportRoute
  AuthenticatedTasksRoute: typeof AuthenticatedTasksRoute
  AuthenticatedTodayRoute: typeof AuthenticatedTodayRoute
  AuthenticatedAdminSupportRoute: typeof AuthenticatedAdminSupportRoute
  AuthenticatedAdminPaymentsRoute: typeof AuthenticatedAdminPaymentsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedBenefitsRoute: AuthenticatedBenefitsRoute,
  AuthenticatedLocalRoute: AuthenticatedLocalRoute,
  AuthenticatedLocalMerchantRoute: AuthenticatedLocalMerchantRoute,
  AuthenticatedDecideRoute: AuthenticatedDecideRoute,
  AuthenticatedHelperDashboardRoute: AuthenticatedHelperDashboardRoute,
  AuthenticatedAdminMarketplaceRoute: AuthenticatedAdminMarketplaceRoute,
  AuthenticatedAdminSafetyRoute: AuthenticatedAdminSafetyRoute,
  AuthenticatedChatRoute: AuthenticatedChatRoute,
  AuthenticatedDocsRoute: AuthenticatedDocsRoute,
  AuthenticatedFamilyRoute: AuthenticatedFamilyRoute,
  AuthenticatedHelpmeRoute: AuthenticatedHelpmeRoute,
  AuthenticatedMoneyRoute: AuthenticatedMoneyRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedSupportRoute: AuthenticatedSupportRoute,
  AuthenticatedTasksRoute: AuthenticatedTasksRoute,
  AuthenticatedTodayRoute: AuthenticatedTodayRoute,
  AuthenticatedAdminSupportRoute: AuthenticatedAdminSupportRoute,
  AuthenticatedAdminPaymentsRoute: AuthenticatedAdminPaymentsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  MicTestRoute: MicTestRoute,
  LineCallbackRoute: LineCallbackRoute,
  SsoCallbackRoute: SsoCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
